### PR TITLE
Update webmock to work on ruby 2.4+

### PR DESCRIPTION
**Pull request by sj26**
I got lots of this while trying to dev on my machine:

```
  1) Cronitor sets its config correctly has the specified options
     Failure/Error:
       response = Unirest.get(
         "#{API_URL}/monitors/#{URI.escape(name).gsub('[', '%5B').gsub(']', '%5D')}",
         headers: default_headers,
         auth: { user: token }
       )

     NoMethodError:
       undefined method `close' for #<StubSocket:0x007f8de75d28a8>
     # ./lib/cronitor.rb:46:in `exists?'
     # ./lib/cronitor.rb:27:in `initialize'
     # ./spec/cronitor_spec.rb:17:in `new'
     # ./spec/cronitor_spec.rb:17:in `block (3 levels) in <top (required)>'
     # ./spec/cronitor_spec.rb:25:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # RestClient::ResourceNotFound:
     #   404 Resource Not Found
     #   ./lib/cronitor.rb:46:in `exists?'
```

Seems to be this issue which is fixed in webmock >= 2.3.1:

https://github.com/bblimke/webmock/issues/683

Simply updating seems to work fine.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
Thanks @sj26! I’ll do some tidying up of the other gems as well, and cut a release.
